-- Entrega Banco de Dados - Modelo Fisico (PostgreSQL)
-- Baseado no schema real da migration InitialCreate

CREATE TABLE IF NOT EXISTS "Clientes" (
    "ClienteId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome" VARCHAR(150) NOT NULL,
    "Email" VARCHAR(200) NOT NULL,
    "SenhaHash" TEXT NOT NULL,
    "Telefone" VARCHAR(20),
    "IsAdmin" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Clientes_Email"
    ON "Clientes" ("Email");

CREATE TABLE IF NOT EXISTS "Entregadores" (
    "EntregadorId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome" VARCHAR(150) NOT NULL,
    "CPF" VARCHAR(14) NOT NULL,
    "Telefone" VARCHAR(20),
    "Veiculo" VARCHAR(100),
    "Disponivel" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Entregadores_CPF"
    ON "Entregadores" ("CPF");

CREATE TABLE IF NOT EXISTS "Restaurantes" (
    "RestauranteId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome" VARCHAR(150) NOT NULL,
    "Descricao" VARCHAR(500),
    "Categoria" VARCHAR(100),
    "ImagemUrl" VARCHAR(255),
    "Endereco" VARCHAR(200),
    "Nota" NUMERIC NOT NULL DEFAULT 0,
    "Ativo" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "Enderecos" (
    "EnderecoId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Logradouro" VARCHAR(200) NOT NULL,
    "Numero" VARCHAR(20) NOT NULL,
    "Complemento" VARCHAR(100),
    "Bairro" VARCHAR(100) NOT NULL,
    "Cidade" VARCHAR(100) NOT NULL,
    "CEP" VARCHAR(10) NOT NULL,
    "ClienteId" INTEGER NOT NULL,
    CONSTRAINT "FK_Enderecos_Clientes_ClienteId"
        FOREIGN KEY ("ClienteId") REFERENCES "Clientes"("ClienteId") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Enderecos_ClienteId"
    ON "Enderecos" ("ClienteId");

CREATE TABLE IF NOT EXISTS "Produtos" (
    "ProdutoId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome" VARCHAR(150) NOT NULL,
    "Descricao" VARCHAR(500),
    "Preco" NUMERIC NOT NULL,
    "ImagemUrl" VARCHAR(255),
    "Categoria" VARCHAR(100),
    "Disponivel" BOOLEAN NOT NULL DEFAULT TRUE,
    "RestauranteId" INTEGER NOT NULL,
    CONSTRAINT "FK_Produtos_Restaurantes_RestauranteId"
        FOREIGN KEY ("RestauranteId") REFERENCES "Restaurantes"("RestauranteId") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Produtos_RestauranteId"
    ON "Produtos" ("RestauranteId");

CREATE TABLE IF NOT EXISTS "Pedidos" (
    "PedidoId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClienteId" INTEGER NOT NULL,
    "RestauranteId" INTEGER NOT NULL,
    "EnderecoId" INTEGER NOT NULL,
    "EntregadorId" INTEGER,
    "Status" INTEGER NOT NULL,
    "ValorTotal" NUMERIC NOT NULL,
    "Observacao" VARCHAR(500),
    "CriadoEm" TIMESTAMPTZ NOT NULL,
    "AtualizadoEm" TIMESTAMPTZ,
    CONSTRAINT "FK_Pedidos_Clientes_ClienteId"
        FOREIGN KEY ("ClienteId") REFERENCES "Clientes"("ClienteId") ON DELETE CASCADE,
    CONSTRAINT "FK_Pedidos_Enderecos_EnderecoId"
        FOREIGN KEY ("EnderecoId") REFERENCES "Enderecos"("EnderecoId") ON DELETE CASCADE,
    CONSTRAINT "FK_Pedidos_Entregadores_EntregadorId"
        FOREIGN KEY ("EntregadorId") REFERENCES "Entregadores"("EntregadorId"),
    CONSTRAINT "FK_Pedidos_Restaurantes_RestauranteId"
        FOREIGN KEY ("RestauranteId") REFERENCES "Restaurantes"("RestauranteId") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Pedidos_ClienteId"
    ON "Pedidos" ("ClienteId");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_EnderecoId"
    ON "Pedidos" ("EnderecoId");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_EntregadorId"
    ON "Pedidos" ("EntregadorId");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_RestauranteId"
    ON "Pedidos" ("RestauranteId");

CREATE TABLE IF NOT EXISTS "ItensPedido" (
    "ItemPedidoId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PedidoId" INTEGER NOT NULL,
    "ProdutoId" INTEGER NOT NULL,
    "Quantidade" INTEGER NOT NULL,
    "PrecoUnitario" NUMERIC NOT NULL,
    "Observacao" VARCHAR(300),
    CONSTRAINT "FK_ItensPedido_Pedidos_PedidoId"
        FOREIGN KEY ("PedidoId") REFERENCES "Pedidos"("PedidoId") ON DELETE CASCADE,
    CONSTRAINT "FK_ItensPedido_Produtos_ProdutoId"
        FOREIGN KEY ("ProdutoId") REFERENCES "Produtos"("ProdutoId") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_ItensPedido_PedidoId"
    ON "ItensPedido" ("PedidoId");
CREATE INDEX IF NOT EXISTS "IX_ItensPedido_ProdutoId"
    ON "ItensPedido" ("ProdutoId");

CREATE TABLE IF NOT EXISTS "Pagamentos" (
    "PagamentoId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PedidoId" INTEGER NOT NULL,
    "Metodo" INTEGER NOT NULL,
    "Status" INTEGER NOT NULL,
    "Valor" NUMERIC NOT NULL,
    "CriadoEm" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "FK_Pagamentos_Pedidos_PedidoId"
        FOREIGN KEY ("PedidoId") REFERENCES "Pedidos"("PedidoId") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Pagamentos_PedidoId"
    ON "Pagamentos" ("PedidoId");
